"use client";
import { useChatLanguage } from "./chat-language";
const topics = [
  ["One link. One conversation.", "Choose a nickname and an optional name. Generate keys & enter opens your conversation immediately. Copy Invite friends above the messages. Guests open that link, generate their own keys and join automatically while an existing participant is online. Everyone has the same rights."],
  ["24 hours. Then gone.", "Everyone shares the deadline shown above the messages. Joining later does not extend it. The relay removes active conversation state at expiry; it has no chat database, archive or recovery service. Reloading keeps your saved session. End session removes its local copy. Expired local records are deleted while the app is open or on the next visit. A server restart also ends active chats."],
  ["Keys change as you talk", "MLS (RFC 9420) authenticates the group and derives message keys in your browser. Joining changes the epoch; active clients also refresh their own key approximately every five minutes. Used message generations and previous epochs are discarded. The relay routes encrypted packets."],
  ["Names are private. Keys identify you.", "Nicknames and the chat name are encrypted. Signed profiles bind aliases to temporary keys. Compare full fingerprints and the conversation code with your friends. A familiar nickname is not proof of a person; clearing the saved session requires a new identity."],
  ["Keep the invitation private", "The link’s secret stays after # and is not uploaded. A separate derived capability authorizes transport. Anyone with the full link can request admission. There is no removal or invitation rotation. If everyone loses their keys, start a new conversation."],
  ["Return without a new identity", "Reopen your link in the same browser: your nickname, keys and received messages return, even after a reload. The encrypted local session expires with the conversation. End session removes it. Site-data clearing and private browsing may prevent recovery. Another device or the onion address uses a separate browser session."],
  ["Who is connected", "Open Participants to see online and disconnected peers. Connection status expires after about 20 seconds without a poll. Pending guests appear separately until their keys are admitted. Status does not revoke a participant’s keys."],
  ["Replies and reactions", "Hold a message on mobile, right-click on desktop, or use its menu button to reply or react. Tap your reaction again to remove it. Both travel inside MLS encryption. Quotes use verified messages already in your tab; guests cannot recover earlier history through a reply."],
  ["Know the boundaries", "This is a browser client: a compromised website or device can read live keys and plaintext. HTTPS exposes a network address to the endpoint; a VPN or Tor changes that network relationship. Recipients can keep copies. Our self-tests are documented openly; they are not an independent audit or a claim to surpass Signal."],
];
const russianTopics = [
  ["Одна ссылка. Одна беседа.", "Укажите никнейм и, если хотите, название беседы. Кнопка «Создать ключи и войти» сразу откроет чат. Скопируйте ссылку через «Пригласить друзей» над сообщениями. Гости откроют её, создадут свои ключи и подключатся, пока кто-то из участников онлайн. Права у всех одинаковые."],
  ["24 часа. Потом всё исчезнет.", "У всех один срок, указанный над сообщениями. Поздний вход не продлевает его. После истечения срока relay удаляет активное состояние беседы. Базы чата, архива и восстановления нет. Перезагрузка сохраняет сессию. «Новый чат» удаляет её локальную копию. Истёкшие записи удаляются в открытом приложении или при следующем посещении. Перезапуск relay тоже завершает активные беседы."],
  ["Ключи обновляются во время беседы", "MLS (RFC 9420) проверяет состав группы и создаёт ключи сообщений в браузере. Подключение участника меняет epoch; активные клиенты также обновляют собственный ключ примерно каждые пять минут. Использованные поколения ключей и прежние epoch удаляются. Relay доставляет зашифрованные пакеты."],
  ["Имена скрыты. Ключи отличают участников.", "Никнеймы и название беседы зашифрованы. Подписанные профили связывают никнеймы с временными ключами. Сверяйте полные fingerprint и код беседы с друзьями. Знакомый никнейм не подтверждает личность; удаление сохранённой сессии потребует новой личности."],
  ["Берегите приглашение", "Секрет ссылки находится после # и не передаётся на сервер. Отдельный производный ключ даёт допуск к доставке. Любой обладатель полной ссылки может запросить вход. Удаления участников и замены приглашения нет. Если все потеряли ключи, создайте новую беседу."],
  ["Возвращайтесь без нового никнейма", "Откройте свою ссылку в том же браузере: никнейм, ключи и полученные сообщения вернутся, даже после перезагрузки. Зашифрованная локальная сессия истекает вместе с беседой. «Новый чат» удаляет её. Очистка данных и приватный режим могут лишить восстановления. Другое устройство или onion-адрес используют отдельную сессию браузера."],
  ["Кто подключён", "Откройте «Участники», чтобы увидеть, кто онлайн и у кого нет связи. Без опроса статус истекает примерно через 20 секунд. Ожидающие гости показываются отдельно, пока их ключи не приняты. Отключение не отзывает ключ участника."],
  ["Ответы и реакции", "Зажмите сообщение на телефоне, нажмите правой кнопкой на компьютере или откройте меню кнопкой у сообщения, чтобы ответить или поставить реакцию. Повторное нажатие уберёт вашу реакцию. Ответы и реакции передаются внутри MLS. Цитаты берутся из проверенных сообщений вашей вкладки; гость не получает через ответ прежнюю историю."],
  ["Помните о границах защиты", "Это браузерный клиент: взломанный сайт или устройство могут прочитать действующие ключи и текст. При HTTPS сетевой узел видит адрес подключения; VPN или Tor меняют эту связь. Получатели могут сохранять копии. Результаты наших проверок открыты, но независимого аудита пока нет. Превосходство над Signal не заявляется."],
];
export function ChatGuide() {
  const { language, t } = useChatLanguage();
  return <div className="chat-guide" lang={language}><p className="chat-eyebrow">{t("HOW SECURE CHAT WORKS", "КАК РАБОТАЕТ SECURE CHAT")}</p><h3>{t("One link. 24 hours.", "Одна ссылка. 24 часа.")}</h3>{(language === "ru" ? russianTopics : topics).map(([title, text], index) => <details key={index} open={index === 0}><summary>{title}<span aria-hidden="true">+</span></summary><div><p>{text}</p></div></details>)}<a className="chat-review-link" href="/secure-chat/security" target="_blank" rel="noreferrer">{t("Security Review / EN · RU ↗", "Проверка защиты / EN · RU ↗")}</a><p className="chat-source-links"><a href="https://www.rfc-editor.org/rfc/rfc9420.html" target="_blank" rel="noreferrer">RFC 9420</a> · <a href="https://github.com/LukaJCB/ts-mls" target="_blank" rel="noreferrer">ts-mls</a></p></div>;
}
