"use client";
const topics = [
  ["One link. One conversation.", "Choose a nickname and an optional name. Generate keys & enter opens your conversation immediately. Copy Invite friends above the messages. Guests open that link, generate their own keys and join automatically while an existing participant is online. Everyone has the same rights."],
  ["24 hours. Then gone.", "Everyone shares the deadline shown above the messages. Joining later does not extend it. The relay removes active conversation state at expiry; it has no chat database, archive or recovery service. Closing or reloading discards this tab’s keys sooner. A server restart also ends active chats."],
  ["Keys change as you talk", "MLS (RFC 9420) authenticates the group and derives message keys in your browser. Joining changes the epoch; active clients also refresh their own key approximately every five minutes. Used message generations and previous epochs are discarded. The relay routes encrypted packets."],
  ["Names are private. Keys identify you.", "Nicknames and the chat name are encrypted. Signed profiles bind aliases to temporary keys. Compare full fingerprints and the conversation code with your friends. A familiar nickname is not proof of a person; a returning user has a fresh key."],
  ["Keep the invitation private", "The link’s secret stays after # and is not uploaded. A separate derived capability authorizes transport. Anyone with the full link can request admission. There is no removal or invitation rotation. If everyone loses their keys, start a new conversation."],
  ["Know the boundaries", "This is a browser client: a compromised website or device can read live keys and plaintext. HTTPS exposes a network address to the endpoint; a VPN or Tor changes that network relationship. Recipients can keep copies. Our self-tests are documented openly; they are not an independent audit or a claim to surpass Signal."],
];
export function ChatGuide() {
  return <div className="chat-guide"><p className="chat-eyebrow">HOW SECURE CHAT WORKS</p><h3>One link. 24 hours.</h3>{topics.map(([title, text], index) => <details key={title} open={index === 0}><summary>{title}<span aria-hidden="true">+</span></summary><div><p>{text}</p></div></details>)}<a className="chat-review-link" href="/secure-chat/security" target="_blank" rel="noreferrer">Security Review / EN · RU ↗</a><p className="chat-source-links"><a href="https://www.rfc-editor.org/rfc/rfc9420.html" target="_blank" rel="noreferrer">RFC 9420</a> · <a href="https://github.com/LukaJCB/ts-mls" target="_blank" rel="noreferrer">ts-mls</a></p></div>;
}
