"use client";
import Link from "next/link";
import { useState } from "react";
import review from "@/docs/secure-chat-v2-review.json";
const actors = {
  en: [
    ["Participant", "Own live keys, readable messages, verified profiles and the invitation", "Can copy anything they receive. A key is a temporary identity."],
    ["Another tab in the same browser", "Readable UI state and commands through a local BroadcastChannel", "One active writer; encrypted local state permits recovery after the owner closes."],
    ["Ciphertext relay", "Routing group, transport keys and grants, encrypted packets, membership operations, size and timing", "No invitation secret, MLS private keys, readable names or message text in the protocol."],
    ["HTTPS edge / hosting network", "Peer network address and traffic characteristics", "Disabled access logs reduce retention; they do not make connections invisible."],
    ["Delivered website / device", "Browser code, plaintext and live cryptographic state", "A compromised client defeats end-to-end encryption at that endpoint."],
    ["Invitation holder", "The ability to request admission before expiry", "Cannot recover earlier message keys from the link alone."],
  ],
  ru: [
    ["Участник", "Собственные действующие ключи, прочитанные сообщения, проверенные профили и приглашение", "Может копировать полученное. Ключ — временная личность."],
    ["Другая вкладка того же браузера", "Открытый текст интерфейса и команды через локальный BroadcastChannel", "Один активный отправитель; зашифрованная локальная запись позволяет вернуться после закрытия вкладки."],
    ["Сервер шифротекста", "Беседа маршрутизации, транспортные ключи и допуски, зашифрованные пакеты, операции входа, размеры и время", "Протокол не передаёт секрет приглашения, приватные MLS-ключи, читаемые имена и сообщения."],
    ["HTTPS-узел / сеть хостинга", "Сетевой адрес подключения и характеристики трафика", "Отключение access-логов уменьшает хранение, но не делает соединение невидимым."],
    ["Код сайта / устройство", "Код браузера, текст и действующее криптографическое состояние", "Взлом клиента нарушает сквозную защиту на этом устройстве."],
    ["Обладатель приглашения", "Возможность запросить вход до истечения срока", "Одна ссылка не восстанавливает ключи прошлых сообщений."],
  ],
};
export function SecurityReviewContent({ onionOrigin }: { onionOrigin?: string }) {
  const [language, setLanguage] = useState<"en" | "ru">("en");
  const ru = language === "ru", { layers, limits } = review[language];
  return <main className="chat-security-page" lang={language}>
    <nav className="chat-security-nav"><Link href="/secure-chat">← dis/root</Link><div className="chat-language-switch" aria-label="Language"><button type="button" aria-pressed={!ru} onClick={() => setLanguage("en")}>EN</button><button type="button" aria-pressed={ru} onClick={() => setLanguage("ru")}>RU</button></div></nav>
    <header className="chat-security-hero"><p className="chat-eyebrow">SECURE CHAT / TECHNICAL SELF REVIEW</p><h1>{ru ? <>Одна ссылка.<br /><span>Проверяемая защита.</span></> : <>One link.<br /><span>Inspect the boundaries.</span></>}</h1><p>{ru ? "Ключи в браузере. Сквозное шифрование MLS. Общий срок до 24 часов. Без аккаунта и серверного архива." : "Keys in your browser. MLS end-to-end encryption. One shared deadline, up to 24 hours. No account. No server archive."}</p><div className="chat-security-badges"><span>MLS / RFC 9420</span><span>24H MAX</span><span>LOCAL RECOVERY</span></div><p className="chat-security-disclaimer">{ru ? "Техническая самопроверка, не независимый аудит. Здесь описаны реализованные механизмы, воспроизводимые тесты и ограничения." : "A technical self-review, not an independent audit. Implemented controls, reproducible tests and explicit limits."}</p><p>{ru ? "Хотите провести аудит или запросить материалы? " : "Want to audit the implementation or request review material? "}<a href="https://t.me/mailsec" target="_blank" rel="noreferrer">Telegram DM ↗</a></p></header>
    {onionOrigin && <p className="chat-onion-link">{ru ? "Вход без раскрытия IP серверу: " : "Keep your IP from the server: "}<a href={`${onionOrigin}/secure-chat`} rel="noreferrer">Tor Browser / .onion ↗</a></p>}
    <section className="chat-security-flow" aria-label={ru ? "Путь сообщения" : "Message path"}><div><small>{ru ? "БРАУЗЕР" : "BROWSER"}</small><strong>{ru ? "Подписать → зашифровать" : "Sign → encrypt"}</strong><p>{ru ? "Ключи остаются здесь" : "Keys remain here"}</p></div><span aria-hidden="true">→</span><div><small>RELAY</small><strong>{ru ? "Доставить → удалить" : "Route → expire"}</strong><p>{ru ? "Шифротекст и метаданные" : "Ciphertext and metadata"}</p></div><span aria-hidden="true">→</span><div><small>{ru ? "ПОЛУЧАТЕЛЬ" : "RECIPIENT"}</small><strong>{ru ? "Проверить → показать" : "Verify → display"}</strong><p>{ru ? "Только проверенный текст" : "Authenticated text only"}</p></div></section>
    <section className="chat-security-section"><p className="chat-eyebrow">{ru ? "ПРОТОКОЛ И ЖИЗНЕННЫЙ ЦИКЛ" : "PROTOCOL AND LIFECYCLE"}</p><h2>{ru ? "Как это работает." : "How it works."}</h2><div className="chat-security-layers">{layers.map(([number, title, body]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
    <section className="chat-security-section"><p className="chat-eyebrow">{ru ? "МОДЕЛЬ УГРОЗ" : "THREAT MODEL"}</p><h2>{ru ? "Кто что видит." : "Who sees what."}</h2><div className="chat-security-table-wrap"><table><thead><tr>{(ru ? ["Участник модели", "Что доступно", "Граница"] : ["Actor", "Can access", "Boundary"]).map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{actors[language].map(([actor, access, boundary]) => <tr key={actor}><td>{actor}</td><td>{access}</td><td>{boundary}</td></tr>)}</tbody></table></div></section>
    <section className="chat-security-section chat-security-limits"><p className="chat-eyebrow">{ru ? "ГРАНИЦЫ ЗАЩИТЫ" : "SECURITY BOUNDARIES"}</p><h2>{ru ? "Условия и ограничения." : "Conditions and limits."}</h2>{limits.map(([title, body], index) => <details key={`${language}-${index}`} open={index === 0}><summary>{title}</summary><p>{body}</p></details>)}</section>
    <section className="chat-security-section"><p className="chat-eyebrow">{ru ? "ПРОВЕРКИ И ОТЧЁТЫ" : "TESTS AND REPORTS"}</p><h2>{ru ? "Проверить самостоятельно." : "Run the checks."}</h2><p>{ru ? "Тесты выполняют реальный код клиента и relay: вход, до 16 участников, подписи, повреждение пакетов, повторную доставку, гонки, одноразовые запросы, лимиты и очистку, зашифрованные ответы и реакции, возврат после перезагрузки, восстановление прерванной отправки, подмену локальной записи и работу нескольких вкладок. Отдельные лабораторные сценарии проверяют MLS после копирования состояния и обновления ключей. Истечение срока проверяется переводом тестовых часов; это не суточный нагрузочный прогон." : "Tests exercise the actual client and relay: onboarding, up to 16 participants, signatures, tampering, retries, races, one-time challenges, bounds and cleanup, encrypted replies and reactions, reload recovery, interrupted-write recovery, local-record tampering and multiple browser views. Separate laboratory fixtures exercise MLS after state capture and key updates. Expiry uses an injected clock; this is not a 24-hour endurance run."}</p><p><a href="/secure-chat/reports/send-recovery.md" target="_blank" rel="noreferrer">{ru ? "Отправка и восстановление сессий ↗" : "Delivery and session recovery ↗"}</a> · <a href="/secure-chat/reports/review-closeout.md" target="_blank" rel="noreferrer">{ru ? "Найденные проблемы и исправления ↗" : "Findings and remediation ↗"}</a> · <a href="/secure-chat/reports/security-tests.md" target="_blank" rel="noreferrer">{ru ? "Результаты и список тестов ↗" : "Results and full test list ↗"}</a> · <a href="/secure-chat/reports/release-checks.md" target="_blank" rel="noreferrer">{ru ? "Браузер, HTTP и Tor ↗" : "Browser, HTTP and Tor ↗"}</a> · <a href="/secure-chat/reports/security-tests.json" target="_blank" rel="noreferrer">JSON / SHA-256 ↗</a></p><p>{ru ? "Отчёт указывает дату, среду запуска, исходные TAP-результаты и хеши проверенного кода. Успешные тесты не доказывают отсутствие всех уязвимостей." : "The report records its date, runtime, raw TAP results and hashes of the tested source. Passing tests does not prove the absence of vulnerabilities."}</p><pre>{"npm ci\nnpm run test:chat:report\nnpm run lint\nnpm run build"}</pre></section>
    <footer className="chat-security-footer"><p><a href="https://github.com/eugeneb1ack/disroot-secure-chat" target="_blank" rel="noreferrer">{ru ? "Исходный код и документация" : "Source and documentation"} ↗</a> · <a href="https://www.rfc-editor.org/rfc/rfc9420.html" target="_blank" rel="noreferrer">RFC 9420</a> · <a href="https://github.com/LukaJCB/ts-mls" target="_blank" rel="noreferrer">ts-mls</a></p><Link href="/secure-chat">{ru ? "Открыть Secure Chat →" : "Open Secure Chat →"}</Link></footer>
  </main>;
}
